name: bloc_arch_flow
description: "A Bloc extension package to easily implement TCA or MVI architecture with Bloc using fpdart."
repository: https://github.com/minhuits/bloc_arch_flow
version: 1.0.0

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.1
  mocktail: ^1.0.4
  meta: ^1.16.0
  bloc_test: ^10.0.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0